#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-fastmatch
Version  : 1.1.6
Release  : 53
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/fastmatch_1.1-6.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/fastmatch_1.1-6.tar.gz
Summary  : Fast 'match()' Function
Group    : Development/Tools
License  : GPL-2.0
Requires: R-fastmatch-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
that require repeated look-ups. It is slightly faster that R's
	built-in match() function on first match against a table, but
	extremely fast on any subsequent lookup as it keeps the hash
	table in memory.

%package lib
Summary: lib components for the R-fastmatch package.
Group: Libraries

%description lib
lib components for the R-fastmatch package.


%prep
%setup -q -n fastmatch
pushd ..
cp -a fastmatch buildavx2
popd
pushd ..
cp -a fastmatch buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735107196

%install
export SOURCE_DATE_EPOCH=1735107196
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fastmatch/DESCRIPTION
/usr/lib64/R/library/fastmatch/INDEX
/usr/lib64/R/library/fastmatch/Meta/Rd.rds
/usr/lib64/R/library/fastmatch/Meta/features.rds
/usr/lib64/R/library/fastmatch/Meta/hsearch.rds
/usr/lib64/R/library/fastmatch/Meta/links.rds
/usr/lib64/R/library/fastmatch/Meta/nsInfo.rds
/usr/lib64/R/library/fastmatch/Meta/package.rds
/usr/lib64/R/library/fastmatch/NAMESPACE
/usr/lib64/R/library/fastmatch/NEWS
/usr/lib64/R/library/fastmatch/R/fastmatch
/usr/lib64/R/library/fastmatch/R/fastmatch.rdb
/usr/lib64/R/library/fastmatch/R/fastmatch.rdx
/usr/lib64/R/library/fastmatch/help/AnIndex
/usr/lib64/R/library/fastmatch/help/aliases.rds
/usr/lib64/R/library/fastmatch/help/fastmatch.rdb
/usr/lib64/R/library/fastmatch/help/fastmatch.rdx
/usr/lib64/R/library/fastmatch/help/paths.rds
/usr/lib64/R/library/fastmatch/html/00Index.html
/usr/lib64/R/library/fastmatch/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/fastmatch/libs/fastmatch.so
/V4/usr/lib64/R/library/fastmatch/libs/fastmatch.so
/usr/lib64/R/library/fastmatch/libs/fastmatch.so
